server.error.whitelabel.enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: semester_work-3
  freemarker:
    expose-request-attributes: true
    enabled: true
    suffix: .ftl
    content-type: text/html
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/books_app
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE
